- name: apt-get update
  command: apt-get update

- name: install mysql
  apt: name=$item state=installed
  with_items:
    - libmysqlclient-dev
    - mysql-server-5.5
    - mysql-client-5.5
    - redis-server
    - monit
    - memcached
    - mongodb-server

- name: set redis.monitrc
  copy: src=redis.monitrc dest=/etc/monit/conf.d
