- name: put .screenrc
  copy: src=screenrc dest=~/.screenrc

- name: put .vimrc
  copy: src=vimrc dest=~/.vimrc

- name: clone ctrlp
  git: repo=git://github.com/kien/ctrlp.vim.git dest=~/.vim/bundle/ctrlp.vim

- name: clone neobundle
  git: repo=git://github.com/Shougo/neobundle.vim.git dest=~/.vim/bundle/neobundle.vim

- name: clone nerdtree
  git: repo=git://github.com/scrooloose/nerdtree.git dest=~/.vim/bundle/nerdtree

- name: clone syntastic
  git: repo=git://github.com/scrooloose/syntastic.git dest=~/.vim/bundle/syntastic

